//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class characterTable
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Race { get; set; }
        public string Class { get; set; }
        public int Level { get; set; }
        public int Experience { get; set; }
        public int Strength { get; set; }
        public int Constitution { get; set; }
        public int Dexterity { get; set; }
        public int Charisma { get; set; }
        public int Wisdom { get; set; }
        public int Intelligence { get; set; }
        public int MaxHP { get; set; }
        public int MaxMana { get; set; }
        public int MaxStamina { get; set; }
        public int userID { get; set; }
    
        public virtual userTable userTable { get; set; }
    }
}
